services:
  rsshub:
    #image: diygod/rsshub:2024-12-14
    image: diygod/rsshub:chromium-bundled-2025-12-15
    restart: unless-stopped
    container_name: rsshub
    hostname: rsshub
    environment:
      - NODE_ENV=production
      - ALLOW_USER_SUPPLY_UNSAFE_DOMAIN=true
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.rsshub.rule=Host(`${RSSHUB_DOMAIN}`)"
      - "traefik.http.routers.rsshub.tls=false"
      - "traefik.http.routers.rsshub.entrypoints=web,websecure"

      - "traefik.http.services.rsshub.loadbalancer.server.port=1200"

      - "traefik.docker.network=traefik-proxy"
    networks:
      - "traefik-proxy"

networks:
  traefik-proxy:
    external: true
