services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    networks:
      - "traefik-proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`${NTFY_DOMAIN}`)"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"
      - "traefik.http.routers.ntfy.entrypoints=web"

      - "traefik.docker.network=traefik-proxy"
    environment:
      - TZ=UTC    # optional: set desired timezone
      - NTFY_BEHIND_PROXY=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${NTFY_CACHE_PATH}:/var/cache/ntfy
      - ${NTFY_CONFIG_PATH}:/etc/ntfy

    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped



networks:
  traefik-proxy:
    external: true
